// Rule codes → tactical descriptors
export const RULE_LABELS = {
  STEP_2_1_PENDING_OT: "ANOMALY-OT-PENDING",
  STEP_2_1_PENDING_LEAVE: "ANOMALY-LEAVE-PENDING",
  STEP_3_1_ERROR_COUNT: "SYS-FLAG-ZOHO-ERR",
  STEP_3_1_MISSING_LOGOUT: "LOG-FAIL-MISSING-OUT",
  STEP_3_1_MISSING_STATUS: "DATA-NULL-STATUS",
  STEP_3_1_MISSING_ACCOUNT: "DATA-NULL-ACCOUNT",
  STEP_3_2_LATE_MINOR: "ANOMALY-LATE-MINOR",
  STEP_3_3_LATE_CRITICAL: "ANOMALY-LATE-CRITICAL",
  STEP_3_4_UNDERTIME_CRITICAL: "ANOMALY-UNDERTIME-CRITICAL",
  STEP_3_5_HALF_DAY_LEAVE: "AUDIT-LEAVE-HALFDAY",
  STEP_3_6_LEAVE_BUT_PRESENT: "AUDIT-CONFLICT-PRESENT",
  STEP_3_9_SCHEDULE_NOT_40H: "RESOURCE-SCHED-ANOMALY",
  STEP_4_1_BREAK_NO_END: "LOG-FAIL-OPEN-BREAK",
  STEP_4_2_CLINIC_OVERTIME: "AUDIT-CLINIC-DURATION",
  STEP_4_3_OVERBREAK: "AUDIT-OVERBREAK-LIMIT",
  STEP_4_5_CLINIC_LUNCH_OVERLAP: "AUDIT-BREAK-OVERLAP",
};

export const SEVERITY_ICONS = {
  HIGH: "[H]",
  MEDIUM: "[M]",
  LOW: "[L]",
};

export function formatDate(dateStr) {
  if (!dateStr) return "N/A";
  const d = new Date(dateStr + "T00:00:00");
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).toUpperCase();
}
